menu:
  Blog: /blog
  Documentation:
    Developer Docs: /developer/getting-started.html
    WIKI:  //github.com/hal/docs/wiki/
  Community:
    Wildfly:  //wildfly.org
    Mailing List:  //lists.jboss.org/mailman/listinfo/wildfly-dev
    IRC:  //freenode.net#wildlfy-management

extmenu:
  Github: //github.com/hal

excerpt_link: Read More

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: false

fancybox: false

google_analytics:
rss:
