menu:
  Blog: /blog/index.html
  Documentation:
    Developer: /developer/1_getting-started.html
    Interface Kernel: /mbui/1_overview.html
    WIKI:  //github.com/hal/docs/wiki/
  Community:
    Issue Tracking: //issues.jboss.org/browse/HAL
    Mailing List:  //lists.jboss.org/mailman/listinfo/wildfly-dev
    IRC:  //freenode.net#wildlfy-management
    Wildfly:  //wildfly.org

extmenu:
  Github: //github.com/hal

excerpt_link: Read More

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: false

fancybox: false

google_analytics: UA-45444197-1
rss:
